menu:
- {name: 'projects', url: '/projects'}
- {name: 'research', url: '/research'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}
- {name: 'interests', url: '/interests'}

projects:
- {name: '3DVLMaps'}

research:
- {interests: 'Machine Learning, Deep Learning, VLMs/Representation Learning'}
- {'coming soon'}

courses:
- {name: 'CSE571: AI-Robotics'}
- {name: 'CSE576: Computer Vision'}
- {name: 'CSE546: Machine Learning'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Andrew Jeon', institution: 'University of Washington', institution_address: '1410 NE Campus Pkwy, Seattle, WA 98195', phone: '(971) 777-1218', personal_email: 'andrewjjeon@gmail.com', email: ajjeon2@uw.edu, image: 'assets/img/contact.png'}
